### ISSUE TITLE
Unclear Directions

### ISSUE THREAD

**Issue by FireAstrox** [yeSpud/CS-372-Project#41]
The instructions for running the project is unclear and does not state that both the front end and backend steps must be done at the same time in separate terminals, if there is way to avoid this it should be listed

Specifically these steps:  
"To start the backend `cd` into the `api` directory in `backend/api` and run `node src/index.js`"
"To build and run the frontend `cd` into the `frontend` directory and run `pnpm dev`"

**Comment by yeSpud** [comment]
running `pnpm dev` in the api directory and the frontend directory can either be done with separate terminals, or can be done with one by running the commands asynchronously with the `&` at the end

**Comment by FireAstrox** [comment]
That should be mentioned in the readme as its not clear

**Comment by yeSpud** [comment]
The read me gives instructions on how to set up and run the project.

It is not meant to give a tutorial on how the terminal works

**Comment by RatKinng** [comment]
Its best practice when writing an installation guide to give all the necessary steps, as unambiguously as possible. If there is extra context needed to understand and execute said steps, that should be included. You are correct that you aren't writing a terminal tutorial, and you shouldn't be, however you should be giving the full, proper steps for installation. If so much context is needed for installation that it begins to look like a terminal tutorial, the process of installation and running should be looked at again in order to better structure your website and documentation for others to use with relative ease and minimal extra context. We had a similar issues with our documentation, however through revision we realized that too much extra context and steps were required, so we revised the install and initial running of the website to make it easier. If your team needs more time to review your documentation and ensure it's correct, then do let us know and we will wait until informed it's ready, as we have done for you, however until that conversation is held we will continue with the expectation that your instructions are fully up to date, and will proceed to raise issues with ambiguous documentation.
